### ISSUE TITLE
[Update Request] V1.20.1 Pretty Please !

### ISSUE THREAD

**Issue by conetopia** [Draylar/go-fish#103]
Very large community pack, complete overhaul, this is the only mod not updated yet.

**Comment by NolanHewitt** [comment]
Hoping for this as well. Only mod I use that's missing an update for 1.20.1

**Comment by MotMomet** [comment]
ye make it happen

**Comment by EnderGirl1500** [comment]
Please dev update us about this version, how long will it take?

**Comment by NolanHewitt** [comment]
pretty sure dev abandoned this. There is a PR with a 1.20.1 version, I built it from the repo and it works just fine in 1.20.1 and includes multiple fixes. I recommend just getting that.

**Comment by zai205** [comment]
where can i find this version

**Comment by NolanHewitt** [comment]
Here: https://github.com/eliskvitka/go-fish/tree/1.20.1

**Comment by InsaanNotFound** [comment]
Can you send over a compiled version? It doesn't work for me.

**Comment by ButterMe8aby** [comment]
A compiled version somewhere would help a lot, I miss fishing in the end.

**Comment by NolanHewitt** [comment]
https://www.curseforge.com/minecraft/mc-mods/go-fish-updated
