### ISSUE TITLE
Can't open crates

### ISSUE THREAD

**Issue by FewerFlaws** [Draylar/go-fish#2]
The tooltip says to shift-click to open a crate.  I've tried the following with wooden crates and iron crates to no avail:
  * Left Click in inventory.
  * Right Click in inventory.
  * Shift + Left Click in inventory.
  * Shift + Right Click in inventory.
  * Left Click placed block.
  * Right Click placed block.
  * Shift + Left Click placed block.
  * Shift + Right Click placed block.
  * Left Click from belt.
  * Right Click from belt.
  * Shift + Left Click from belt.
  * Shift + Right Click from belt.
  * Mine placed block with pickaxe.
  * Mine placed block with axe.

**Comment by Draylar** [comment]
If [this (shift-click while looking into air)](https://streamable.com/0jkz49) does not work for you, please send your game log through [hastebin](https://hastebin.com/).

**Comment by FewerFlaws** [comment]
Well that worked.  Sometimes you think you've tried everything... >_>
