### ISSUE TITLE
Biome specific fish and crates unable to be obtained without /fish command?

### ISSUE THREAD

**Issue by swinemm** [Draylar/go-fish#23]
I've been using the mod on a server with friends and I have been unable to obtain the biome specific crates/fish without using the /fish command. Everything else works fine, it's only the swamp, ice, and soul sand valley fish/crates (which I think are the only biome specific ones) that seem to be unobtainable.

**Comment by Draylar** [comment]
Do you have another fishing mod installed, such as Netherite Plus?

**Comment by swinemm** [comment]
I actually did have that installed, although I tried removing it and just using this mod in a new world and I got the same results

**Comment by MitztheKat** [comment]
[latest.log](https://github.com/Draylar/go-fish/files/6462445/latest.log)
I doubt this will help but i fished a few times.

[latest.log](https://github.com/Draylar/go-fish/files/6462446/latest.log)
this is the latest log for the server. prolly won't help either.

**Comment by Draylar** [comment]
Biome-specific fishing has been fixed in the next update, thanks for the report.
