### ISSUE TITLE
Cant fish any biome specific mobs in the nether

### ISSUE THREAD

**Issue by Mixelsrock** [Draylar/go-fish#25]
We have just started using this fishing mod on a server and we cant find anything like soul crates or soul salmon even though we are in the correct biome, /fish works but why would we use that? whats the point of even getting fishing rods? We have the better nether mod so that could be the case, we also havent tried fishing for any biome specific items in the overworld yet so that may not work either.

**Comment by Draylar** [comment]
[game logs, please](https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/)

**Comment by Draylar** [comment]
Fixed in the next update~
