### ISSUE TITLE
Go-Fish conflicts with Polymorph, causing crash on startup.

### ISSUE THREAD

**Issue by Bibblyboob** [Draylar/go-fish#30]
Here's the crash report.
[crash-2021-05-09_23.03.11-client.txt](https://github.com/Draylar/go-fish/files/6449150/crash-2021-05-09_23.03.11-client.txt)

Latest log file:
[latest.log](https://github.com/Draylar/go-fish/files/6449114/latest.log)

**Comment by Draylar** [comment]
Update Cardinal Components to 2.8.2 or downgrade Fabric API to <34, this is not a Go Fish or Polymorph problem (Polymorph includes CCA iirc, but it is not polymorph)
