### ISSUE TITLE
Cry, pain and fishburger without fish ;c

### ISSUE THREAD

**Issue by szumaster** [Draylar/go-fish#31]
Referring to #30 

Crash at launch reports:
Fabric API 0.34.2 + CC 2.8.2 = https://pastebin.com/fU4YUeSJ
Fabric API 0.34.2 + CC 2.8.0 = https://pastebin.pl/view/709e71ec
Fabric API 0.34.1 + CC 2.8.2 = https://pastebin.com/SSVe47tN
Fabric API 0.34.0 + CC 2.8.2 = https://pastebin.com/AU74EcBJ 
Fabric API 0.33.1 + CC 2.8.2 = https://pastebin.com/MN2tzK2W
Fabric API 0.33.1 + CC 2.8.1 = https://pastebin.com/E8tCE8Vj
Fabric API 0.33.1 + CC 2.8.0 = https://pastebin.com/MVMC3XFN

**Comment by Draylar** [comment]
Update [Blame](https://github.com/TelepathicGrunt/Blame/issues/35). Thanks for the versioned logs.
