### ISSUE TITLE
No chance on receiving Gilded Blackstone Crate.

### ISSUE THREAD

**Issue by XeroShi** [Draylar/go-fish#33]
Been Fishing for around an hour and cannot obtain the Gilded Blackstone Crate. 
I've been fishing in the Basalt Deltas Biome in the Nether and been using a Luck of the Sea 3 Diamond rod and still have not received the crate despite meeting the requirements. 
I believe there's a compatibility issue with Biome Makeover.

**Comment by Draylar** [comment]
Fixed in the next update, thanks.
