### ISSUE TITLE
Fishing rods not working

### ISSUE THREAD

**Issue by Gam3Crusher** [Draylar/go-fish#40]
When im on a server using this mod, everytime i try use a fishing rod the lure gets launched but then disappears instantly, why is this happening as it works fine on singleplayer until i put this mod on my multiplayer world.

**Comment by jangro** [comment]
Came here to see if this is a thing. It's happening to me too. I installed the mod to test it out on my server/client. This exact thing happened. I removed it, and it's still happening so now fishing rods seem to be permanently broken. I don't even know how that's possible. 

There are lots of other mods in play here as I added it on top of Valhelsia Fabric 1.0.6 modpack.

This gives me some ideas to test, like maybe I'll try copying my world to local singleplayer.

**Comment by jangro** [comment]
...and I updated to Valhelsia Fabric 1.0.7 and the problem is gone. Can't be sure why. Fabric was updated, many mods were updated. Go Fish still isn't installed. I'll try putting it back at some point.

**Comment by FigaroGarcia** [comment]
> 
> 
> ...and I updated to Valhelsia Fabric 1.0.7 and the problem is gone. Can't be sure why. Fabric was updated, many mods were updated. Go Fish still isn't installed. I'll try putting it back at some point.

Did you ever put it back into the world? Im experiencing the same thing in a multiplayer world, and even after refreshing the world (essentially backing up our world with progress and generating a new one) + removing the mod it's still broken. It might be some weird conflict with some mods I have, so I was gonna go check out the modpack and see if any Ive thrown into our server may be the cause of it instead.

**Comment by FigaroGarcia** [comment]
> 
> It might be some weird conflict with some mods I have, so I was gonna go check out the modpack and see if any Ive thrown into our server may be the cause of it instead.

Found the problem, it appears to just be Black Powder (gun mod). I imagine it did something to right click mechanics, as the guns had a hold-to-reload type deal. If you have a mod that has a similar mechanic alongside Go Fish, it could be a strange right-click bug from the mod itself. 
For any others that might be experiencing this, I'm playing on Fabric 1.17.1 (0.12.5) on a multiplayer server with a pretty random selection of mods. If you're experiencing this bug on single player, you might have to do some more process-of-elimination experimenting to fix it.

**Comment by Draylar** [comment]
Seems to be an issue with a library Black Powder is using - see their issue tracker for details.
