### ISSUE TITLE
Go fish don't work

### ISSUE THREAD

**Issue by ghost** [Draylar/go-fish#41]
I have a fabric modpack for minecraft 1.16.5, and this mod crashes, please help
Link: https://gist.githubusercontent.com/natanfudge/f1c83503a55fd7ac58da4ec339138007/raw/1102befe5054c753a6f5346a6aaa52b88507c089/crash.txt

**Comment by ghost** [comment]
maybe this is'nt problem this mod

**Comment by ghost** [comment]
how to delete this

**Comment by Draylar** [comment]
If you haven't fixed the issue yet, you need to update CCA to [~2.8.3](https://github.com/OnyxStudios/Cardinal-Components-API/releases/tag/2.8.3). You should be able to install that jar & drop it into your mod folders. I am not sure why Go Fish is appearing in the log.
