### ISSUE TITLE
missing items: charfish, seaweed eel, matrix rod, and eye of fishing

### ISSUE THREAD

**Issue by rosedragon** [Draylar/go-fish#46]
Hi,

I got everything except charfish, seaweed eel, matrix rod, and eye of fishing. Can someone clarify if they are attainable and give a little clue how?

Thanks!

**Comment by Draylar** [comment]
Whoops, forgot to add the Charfish & Seaweed Eel drops! You can now obtain Charfish by smelting Oakfish in a furnace.
Seaweed Eels can be caught in oceans. 

I'm going to hold off on adding loot drops for the Eye of Fishing & Matrix items until I add a crate for the end, so I will keep this issue open until that is done. Thanks for the report!

**Comment by rosedragon** [comment]
Thank you! Loving the mod especially the cloud crab and full-moon fishing :D !

**Comment by Draylar** [comment]
Eye of Fishing & Matrix items will be obtainable in End Crates in the next update :)
