### ISSUE TITLE
Shifft + click on crate is broken

### ISSUE THREAD

**Issue by itsdinkd** [Draylar/go-fish#48]
1.17.1
Latest GoFish
Fabric
-

Shift + clicking on a crate does not do anything. I've tried with crate on hotbar, in inventory (it adds the item to inventory from hot/action bar, and visa versa) 

Maybe due to incompatibility with inventory sort or Item Scroller?

**Comment by Anubeia** [comment]
Took me about 5 minutes of fiddling, you need to shift-click with it in your hand, but not while looking at a block.

**Comment by Draylar** [comment]
Here's a video of how to open it -> https://streamable.com/0jkz49
