### ISSUE TITLE
Rods dont support Rod enchantments

### ISSUE THREAD

**Issue by milkev** [Draylar/go-fish#5]
none of the fishing rods from the mod seem to support enchantments other than unbreaking and mending, even the mods own enchantment, deepfry.

**Comment by Draylar** [comment]
Waiting on [FAPI#1102](https://github.com/FabricMC/fabric/pull/1102) for this, which will hopefully be merged soon.

**Comment by Draylar** [comment]
Oh, I just realized my fishing rods are... for some reason, not actually fishing rods. I'm hoping nothing else broke by doing this, but it seems to work now:

![image](https://user-images.githubusercontent.com/17728338/105276229-7e60d880-5b66-11eb-8574-383d676758fe.png)

Out in the next release~
