### ISSUE TITLE
Crates do not drop items on mining anymore

### ISSUE THREAD

**Issue by TestSerber** [Draylar/go-fish#50]

**Comment by gildervine** [comment]
can confirm on mc1.17.1 v0.9.3 - i placed crates and could only get the wooden one to drop as an item
iron and gold crates disappeared, even using a diamond pick

**Comment by Draylar** [comment]
Break time & tools weren't properly configured on my side - this will be fixed in 1.3.1 beta for 1.17.1, which will be out in a second.
