### ISSUE TITLE
Added items from the mod dont show up. (Mod is installed on a Server)

### ISSUE THREAD

**Issue by sightstorm** [Draylar/go-fish#53]
Not sure if this mod is able to be run on a server. But It does register the catch. As I received the achievement for catching an iron crate. Although the achievement did lack the image of the crate and everything was in command brackets. The thing is, Although I got the achievement I did not get the item in question. So that makes be believe its missing in the server item library.

It could be the fact that I miss a certain mod that helps new items to get correctly implemented on the server. If that is the issue of the problem I would like to know what mod helps to have new items from other mods get correctly implemented.

If its not the case I hope that this mod would be soon made compatible with servers. Because its a really fun fishing mod.

**Comment by Draylar** [comment]
Make sure you have the mod on the server **and** client. It sounds like you only have Go Fish installed on the server. If you are sure you have Go Fish installed on both sides, please send your client/server game logs through a service such as [pastebin](https://pastebin.com/).
