### ISSUE TITLE
Can't open chests with shift-click with other mods

### ISSUE THREAD

**Issue by Rychlas** [Draylar/go-fish#64]
Hello, apparently whenever other mods also use shift-click, for example EQ sorting mods, it breaks your chests and you can no longer open any chests. Could you please make it so that if you righclick on a placed box or crouch-rightclick when holding the chest you can open it too? I'd love to test out your mod but I really want to have a sorting mod too.

**Comment by Draylar** [comment]
Have you tried opening it as demonstrated in [this clip](https://streamable.com/0jkz49)?

**Comment by Rychlas** [comment]
It actually did work, rightclick when I'm crouching. I'm not sure whether it worked because I got rid of one mod or not, I'll have to check later. Can't wait to catch some goodies soon. Cheers!
