### ISSUE TITLE
1.18.2+ support

### ISSUE THREAD

**Issue by AugustusZebulon** [Draylar/go-fish#67]
Hi guys!

I enjoy this mod very much and thank you for making it!
I was able to load it up just fine on 1.18.1 but it does not load at all at 1.18.2.
The mod starts loading and then crashes.
Just wanted to ask is there a plan to upgrade it for 1.18.2?

Thank you in advance!

**Comment by Draylar** [comment]
Out now for 1.18.2, have fun fishing!
