### ISSUE TITLE
Questions about Vanilla Enchantments + Suggestion

### ISSUE THREAD

**Issue by DjJpGamer** [Draylar/go-fish#8]
Hello there! I was using your mod for the past 2 weeks and I enjoyed it a lot, but I have a question: Why doesn't the enchantments "Luck of the sea" and "Lure" apply on the mod fishing rods? Is it because of the items that already give those stats?

**Comment by Draylar** [comment]
IIRC, I fixed this in the 1.2.0 release (released 3 days ago). Give that release a try and let me know if you encounter any other issues with enchantments. Thanks for the report!
