### ISSUE TITLE
Lure above 5 is broken

### ISSUE THREAD

**Issue by SCPRedMage** [Draylar/go-fish#95]
A known issue in vanilla Minecraft is if the Lure enchantment is added at a level above five, the wait time never actually starts, and thus fish never bite, completely breaking fishing. Normally this wouldn't be achievable, however with other mods plus lures from Go Fish, it's easily possible to exceed that.

Please add a limit to the lure variable to prevent it from exceeding 5, after all bonuses are applied.

EDIT: Due to bonusLuck being added to lure as described in #96 you can exceed Lure 5 with a Lure 3 rod, a Simple Lure, a Golden Fish, and a Soul Lure, while standing in a Soul Sand Valley, making it possible to break this limit using just Go Fish.

**Comment by KuwuroUsagi** [comment]
You perfectly defined why #85 seemed to happen, I do hope they can fix/address this so others don't encounter the problem.

**Comment by SCPRedMage** [comment]
This is actually a known vanilla issue, it just isn't possible in vanilla to go above Lure 3 without using commands.
